---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: document-summarizer
  name: document-summarizer
spec:
  selector:
    app: document-summarizer
  ports:
    - protocol: TCP      
      port: 5000
      targetPort: 5000
  type: LoadBalancer

